server:
  port: 8081

spring:
  application:
    name: park-service

  jpa:
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
security:
  jwt:
    secret: ${JWT_SECRET}
    lifetime: 1
