server:
  port: 8081

spring:
  application:
    name: park-service

  jpa:
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/park_repository
    username: postgres
    password: 123456789

  flyway:
    enabled: true
    locations: classpath:db
    url: jdbc:postgresql://localhost:5432/park_repository
    user: postgres
    password: 123456789
security:
  jwt:
    secret: FSDKJKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJALKJFKLAJFSFHAJHDJFHSJHFJHFJSKHKJDFHSJKDHFJSHFKDJHFSFSDFS
    lifetime: 1
